In [1]:
import sys
import numpy as np

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B = np.full((2, 3), 5)
B

array([[5, 5, 5],
       [5, 5, 5]])

In [7]:
v = np.array([6, 7, 8])
v

array([6, 7, 8])

In [8]:
A + B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
A - B

array([[-4, -3, -2],
       [-1,  0,  1]])

In [10]:
A * B

array([[ 5, 10, 15],
       [20, 25, 30]])

In [11]:
A / B

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [12]:
np.dot(A, v)

array([ 44, 107])

In [13]:
A @ v

array([ 44, 107])

In [14]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
C = np.arange(1, 10).reshape((3, 3))
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
D = np.array([
    [1, 2],
    [3, 4]
])
D

array([[1, 2],
       [3, 4]])

In [22]:
np.linalg.det(D)

-2.0000000000000004

In [23]:
np.linalg.inv(D)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [26]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [29]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.empty(5) #not initialized, the value is random as the memory is

array([1., 1., 1., 1., 1.])

In [36]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [37]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [39]:
np.random.random((2, 2))

array([[0.62069084, 0.1647531 ],
       [0.15148317, 0.97606234]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])